env:
  global:
    - MAKEFLAGS="-j4"
sudo: required
dist: trusty

language: rust
rust:
  - stable

addons:
  apt:
    packages:
      - binutils-dev
      - build-essential
      - cmake
      - gcc
      - git
      - libavcodec-dev
      - libavformat-dev
      - libcurl4-openssl-dev
      - libdc1394-22-dev
      - libdw-dev
      - libelf-dev
      - libgmp-dev
      - libgtk2.0-dev
      - libiberty-dev
      - libjasper-dev
      - libjpeg-dev
      - libleptonica-dev
      - libpng-dev
      - libswscale-dev
      - libtbb-dev
      - libtbb2
      - libtesseract-dev
      - libtiff-dev
      - pkg-config
      - tesseract-ocr
      - xvfb

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - export RUSTCV_CAFFE_TEST_FILES=$HOME/testdata
  - sudo -E ./.ci/install_cuda.sh
  - sudo -E ./.ci/travis_build_opencv.sh
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/lib/x86_64-linux-gnu
  - cargo install cargo-travis || echo "cargo-travis already installed"
  - rustup component add rustfmt-preview
  # For headless testing of the sample application (cv::imshow)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo build --features cuda
  - cargo test
  - cargo test -- --ignored
  - cargo doc -p opencv-sys --features cuda --no-deps
  - cargo doc -p rustcv --features cuda --no-deps
  - |
    cargo coverage --verbose &&
    bash <(curl -s https://codecov.io/bash) -s target/kcov -t $CODECOV_TOKEN

notifications:
  email:
    on_success: never

cache:
  timeout: 1000
  cargo: true
  directories:
    - $HOME/usr/installed-version
    - $HOME/usr/include
    - $HOME/usr/lib
    - $HOME/testdata

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/doc/
  on:
    branch: master
